# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# OpenAPI
springdoc.api-docs.enabled=false

# Server Port
server.port=8080

# Logging
logging.level.org.springframework=INFO
logging.level.fr.mb.auth=INFO
logging.level.com.zaxxer.hikari=INFO

# JDBC DataSource
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10