# Spring Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JDBC DataSource
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

# Server Port
server.port=8080

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Logging
logging.level.org.springframework=INFO
logging.level.fr.mb.auth=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari=INFO