spring.application.name=auth

# Default Profile
spring.profiles.default=dev

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# JDBC DataSource
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000